#Grab map files from legacy servers, and compare.

---

- hosts: non_aws_legacy:aws_legacy
  become: yes
  become_user: vcs2vcs
  tasks:
    - name: pack mapfiles
      command: tar czf /tmp/ansible.tgz *-mapfile
      args:
        chdir: /tmp/vcs-sync
        creates: /tmp/ansible.tgz
        warn: False
    - name: fetch created tarball
      fetch: 
        src: /tmp/ansible.tgz
        dest: fetch/{{ inventory_hostname }}.mapfile.tgz
        flat: yes
        fail: yes
    - name: remove file
      file: >
        path=/tmp/ansible.tgz
        state=absent

- hosts: localhost
  tasks:
    - file: path=fetch/prod state=directory
    - name: expand production files
      command: tar xzf fetch/{{ item }}.mapfile.tgz -C fetch/prod
      args:
        warn: False
      with_items: 
        - gd1
        - gd3
    - file: path=fetch/stage state=directory
    - name: expand staging files
      command: tar xzf fetch/{{ item }}.mapfile.tgz -C fetch/stage
      with_items: 
        - vsl
    - name: checking for diffs
      command: diff -r --brief fetch/prod fetch/stage
      args:
        warn: False
    - name: check sizes
      tags: check
      shell: wc -l * >../wc.{{ item }}
      args:
        chdir: fetch/{{ item }}
      with_items:
        - prod
        - stage
